name: 'blackduck-report-action'
description: 'Create Black Duck Report and download it'
author: "Jeroen Knoops <jeroen.knoops@philips.com>"
branding:
  icon: "anchor"
  color: "gray-dark"
inputs:
  blackduck-url:
    description: 'url to Black Duck instance'
    required: true
  blackduck-token:
    description: 'Black Duck API token'
    required: true
  project:
    description: 'Project name in Black Duck'
    required: true
  version:
    description: 'Version in Black Duck'
    required: true
  report-format:
    description: 'sbomType "SPDX_22" allows reportFormat values of "JSON", "RDF", "TAGVALUE" or "YAML". sbomType "CYCLONEDX_13" or "CYCLONEDX_14" allows reportFormat values of "JSON".'
    default: "JSON"
  sbom-type:
    description: 'Type of SBOM report. Allowed values - SPDX_22, CYCLONEDX_13 or CYCLONEDX_14'
    default: "SPDX_22"
outputs:
  sbom-file:
    description: 'SBOM filename if created'
  sbom-contents:
    description: 'SBOM content if created'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.blackduck-url }}
    - ${{ inputs.blackduck-token }}
    - ${{ inputs.project }}
    - ${{ inputs.version }}
    - ${{ inputs.sbom-type }}
    - ${{ inputs.report-format }}
